print("Welcome to the Grade Sorter App")
print()
grades = []
print()
grades = []
grades.append(int(input("What is your first grade (0-100): ")))
grades.append(int(input("What is your second grade (0-100): ")))
grades.append(int(input("What is your third grade (0-100): ")))
grades.append(int(input("What is your fourth grade (0-100): ")))
print()
print("Your grades are: {}".format(grades))
print()
grades.sort(reverse=True)
print("Your grades from highest to lowest are: {}".format(grades))
print()
print("The lowest two grades will now be dropped")
lowerGrade1 = grades.pop()
lowerGrade2 = grades.pop()
print("Removed grade: {}".format(lowerGrade1))
print("Removed grade: {}".format(lowerGrade2))
print()
print("Your remaining grades are: {}".format(grades))
grades.sort()
best = grades.pop()
print("Nice work! Your highest grade is a {}".format(best))