print("Welcome to the Multiplication/Exponent Table App")
print()
name = input("Hello, What is your name: ")
number = float(input("What number would you like to work with: "))
name = name.strip()

print("Multiplication Table For {}".format(number))
print()
print("\t\t1.0 * {} = {:.2f}".format(number, number*1.0))
print("\t\t2.0 * {} = {:.2f}".format(number, number*2.0))
print("\t\t3.0 * {} = {:.2f}".format(number, number*3.0))
print("\t\t4.0 * {} = {:.2f}".format(number, number*4.0))
print("\t\t5.0 * {} = {:.2f}".format(number, number*5.0))
print("\t\t6.0 * {} = {:.2f}".format(number, number*6.0))
print("\t\t7.0 * {} = {:.2f}".format(number, number*7.0))
print("\t\t8.0 * {} = {:.2f}".format(number, number*8.0))
print("\t\t9.0 * {} = {:.2f}".format(number, number*9.0))
print()
print("Exponent Table For {}".format(number))
print()
print("\t\t{} ** 1 = {:.2f}".format(number, number**1))
print("\t\t{} ** 2 = {:.2f}".format(number, number**2))
print("\t\t{} ** 3 = {:.2f}".format(number, number**3))
print("\t\t{} ** 4 = {:.2f}".format(number, number**4))
print("\t\t{} ** 5 = {:.2f}".format(number, number**5))
print("\t\t{} ** 6 = {:.2f}".format(number, number**6))
print("\t\t{} ** 7 = {:.2f}".format(number, number**7))
print("\t\t{} ** 8 = {:.2f}".format(number, number**8))
print("\t\t{} ** 9 = {:.2f}".format(number, number**9))
print()
message = "{} Math is cool!".format(name)

print(message)
print("\t{}".format(message.lower()))
print("\t\t{}".format(message.title()))
print("\t\t\t{}".format(message.lower()))